---
title: "Topological Data Analysis - New York City Collision"
author: "Marjorie Blanco"
date: "11/20/2018"
output: html_document
---

```{r setup, include=FALSE}
# Clear packages 
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(
  paste("package:", names(sessionInfo()$otherPkgs), sep=""), 
  detach, character.only = TRUE, unload = TRUE)

# Clear environment
rm(list = ls(all = TRUE))
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(TDA)
library(dplyr)
library(ggplot2)
library(ggmap)
library(TDAmapper)
library(igraph)
```

```{r, error=FALSE, message=FALSE, warning=FALSE}
nyc <- ggmap(get_googlemap(center = c(lon = -74.0060, lat = 40.7128),
                    key = "AIzaSyBlh3p_FmzjhFiOZPT558VfInF1fWWoZps",
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))


NYC_Collisons <- read_excel("NYC_Collisons.xlsx")
NYC_Collisons <- NYC_Collisons %>% filter(!is.na(NYC_Collisons$Longitude))

NYC_Collisons$PersonsInjured <- as.integer(NYC_Collisons$PersonsInjured)

qmplot(Longitude, Latitude, data = NYC_Collisons)

X <- NYC_Collisons %>%  mutate(x = Longitude, y = Latitude) %>% select(x,y)

qplot(X$x, X$y)

NYC_Collisons.dist = dist(X)


for (i in 0:15) {
  m1 <- mapper1D(
    distance_matrix = NYC_Collisons.dist,
    filter_values = NYC_Collisons$Latitude,
    num_intervals = 5+i,
    percent_overlap = 50,
    num_bins_when_clustering = 5)
  g1 <- graph.adjacency(m1$adjacency, mode="undirected")
  plot(g1, layout = layout.auto(g1) )
}


nyc + geom_point(aes(x = x, y = y), data = X) + 
  theme(legend.position="bottom")


X <- NYC_Collisons %>% filter(PersonsInjured != 0) %>%  mutate(x = Longitude, y = Latitude) %>% select(x,y) 

qplot(X$x, X$y)

NYC_Collisons.dist = dist(X)

for (i in 0:15) {
  m1 <- mapper1D(
    distance_matrix = NYC_Collisons.dist,
    filter_values = X$y,
    num_intervals = 5+i,
    percent_overlap = 50,
    num_bins_when_clustering = 5)
  g1 <- graph.adjacency(m1$adjacency, mode="undirected")
  plot(g1, layout = layout.auto(g1) )
}

nyc + geom_point(aes(x = x, y = y), data = X) + 
  theme(legend.position="bottom")

X <- NYC_Collisons %>% filter(PersonsInjured == 0) %>%  mutate(x = Longitude, y = Latitude) %>% select(x,y) 

qplot(X$x, X$y)

NYC_Collisons.dist = dist(X)

for (i in 0:15) {
  m1 <- mapper1D(
    distance_matrix = NYC_Collisons.dist,
    filter_values = X$y,
    num_intervals = 5+i,
    percent_overlap = 50,
    num_bins_when_clustering = 5)
  g1 <- graph.adjacency(m1$adjacency, mode="undirected")
  plot(g1, layout = layout.auto(g1) )
}

nyc + geom_point(aes(x = x, y = y), data = X) + 
  theme(legend.position="bottom")

  
library("TDA")
X1=cbind(rnorm(300,1,.8),rnorm(300,5,0.8))
X2=cbind(rnorm(300,3.5,.8),rnorm(300,5,0.8))
X3=cbind(rnorm(300,6,1),rnorm(300,1,1))
XX=rbind(X1,X2,X3)
Tree=clusterTree(XX, k=100, density="knn")
plot(Tree, type="lambda", main="lambda Tree (knn)")

Tree=clusterTree(X, k=10, density="knn")



persist <- function(nyc_data){

    #We point out that the columns are only the spatial coordinates
    #You can find how to construct this example in TDA package documentation
  #nyc_data <- NYC_Collisons

    vehic_vector <- cbind("V1" = nyc_data$Longitude, "V2" = nyc_data$Latitude)
    Xlim <- c(min(nyc_data$Longitude), max(nyc_data$Longitude))
    Ylim <- c(min(nyc_data$Latitude), max(nyc_data$Latitude))
    by <- 0.002
    x_step <- seq(from = Xlim[1], to = Xlim[2], by = by)
    y_step <- seq(from = Ylim[1], to = Ylim[2], by = by)
    grid <- expand.grid(x_step, y_step)
    diag <- gridDiag(X = vehic_vector, FUN = distFct, lim = cbind(Xlim, Ylim), by = by,
                 sublevel = FALSE, library = "Dionysus", printProgress = FALSE)
    # Since gridDiag returns a list, we access this in any way we want:
    diagram <- diag[["diagram"]]
    topology <- data.frame(cbind("dimension"=diagram[,1],"death"=diagram[,2],"birth"=diagram[,3]))
    return(topology)
    }
# Use the function
persistence <- persist(NYC_Collisons)

```



